### ISSUE TITLE
Remove one of the auth charter docs ... names differ only in case

### ISSUE THREAD

**Issue by zimeon** [IIIF/auth#4]
Rob... assuming this is some mac/linux thing. We have both 

https://github.com/IIIF/auth/blob/master/IIIF_Authentication_Working_Group_Charter.md
and
https://github.com/IIIF/auth/blob/master/iiif_authentication_working_group_charter.md

which means one can't even check out the repo in a consistent state on a dumb kinda-case-sensitive-but-not-really Mac.

**Comment by azaroth42** [comment]
Yeah, will kill both of them.  Was using it to test the google docs to markdown to github script.

**Comment by jpstroop** [comment]
The lower case one is one I hand-crafted. We should keep that, I think?

**Comment by jpstroop** [comment]
(see #3)

**Comment by azaroth42** [comment]
We should decide whether the github markdown version or the google doc version is the current baseline for edits then!

**Comment by jpstroop** [comment]
Bah....I started to look for a watermark the docs yesterday and then got distracted. I vote we use the Github version starting . . . now!

**Comment by jpstroop** [comment]
ARRRGGH! Wait...I'm a tool. I was thinking about the use cases doc from London--that's the one I migrated by hand. I think the charter should stay in google docs for now; non-githubbers may want to make edits/comment and that's a much better platform for it.

**Comment by zimeon** [comment]
I've deleted one of the copies, I'm fine if we want to stay in google docs and delete the second or mark it is a dump of the live doc.

**Comment by azaroth42** [comment]
Closed no?

**Comment by zimeon** [comment]
Agreed
